name: flutter_pick_file
description: The demo project for the wechat_assets_picker package.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.17.0 <3.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  wechat_assets_picker:
  wechat_camera_picker: ^3.6.0

  package_info_plus: ^1.4.2
  path: ^1.8.0
  path_provider: ^2.0.8
  provider: ^6.0.2
  transparent_image: ^2.0.0
  image_picker: ^0.8.6
  widgets_to_image: ^0.0.2
  gallery_saver: ^2.3.2
  screenshot: ^1.2.3
  sn_progress_dialog: ^1.0.8
  video_player: ^2.4.8
  extended_image: ^6.3.2

flutter:
  uses-material-design: true
  assets:
    - assets/
